- rest:
    openApi:
      missingOperation: mock
      specification: api-registry/product-page-api.json
- route:
    id: route-endpoint-4325
    description: Route /path
    from:
      uri: direct:operationIdUpdateMe
      parameters: {}
      steps:
        - unmarshal:
            json:
              library: Jackson
        - log:
            message: "${body}"
        - setBody:
            simple: '{"received": true }'
